name: "❓ Question / Help"
description: "Ask a question or get help using the Scryfall Scrapper"
title: "[Question] "
labels:
  - question
assignees:
  - laryziinha

body:
  - type: markdown
    attributes:
      value: |
        Have a question about how something works?
        This template is for usage questions, clarification, or help.
        If you found a bug or want to suggest a change, please use the other templates.

  - type: dropdown
    id: topic
    attributes:
      label: What is your question about?
      options:
        - General usage
        - SET downloads
        - ALL SETs / batch mode
        - Sets.txt workflow
        - Tokens (DToken.py)
        - Singles (SingleCard.py)
        - Forge Audit integration
        - Printed-name / Secret Lair behavior
        - Errors / unexpected results
        - Installation / environment
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your question
      description: |
        Ask clearly what you are trying to do or understand.
        Include relevant context if possible.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context (optional)
      description: |
        Logs, screenshots, file names, or any other details that help explain the situation.